---
- name: run bash function from shell
  hosts: app
  gather_facts: false

  tasks:
    - name: make sure function is in bashrc
      blockinfile:
        dest: ~/.bashrc
        block: |-
          my_test_func() {
            echo hello test func
          }
    - name: run the function from shell after sourcing .bashrc
      shell: . ~/.bashrc && my_test_func
      register: func_result

    - name: check result
      debug:
        var: func_result.stdout
