---
- name: Download and Extract Tar file
  hosts: app
  become: yes
  become_method: sudo
  vars: 
    tar_url: "https://go.dev/dl/go1.23.0.linux-amd64.tar.gz"
    download_dest: "/home/go/Pkgs"
    tar_file: "go1.23.0.linux-amd64.tar.gz"
    extract_dest: "/usr/local"

  tasks:
      - name: Install tar Package
        apt:
          name: tar
          state: present
          update_cache: yes

      - name: Create Downloads directory
        file:
          path: "{{ download_dest }}"
          state: directory
          mode: "0755"
          recurse: yes

      - name: Download go tar file
        get_url:
          url: "{{ tar_url }}"
          dest: "{{ download_dest }}"

      - name: Extract tar file
        unarchive:
          src: "{{ download_dest }}/{{ tar_file }}"
          dest: "{{ extract_dest }}"
          remote_src: yes

      - name: Run go version
        command: go version
        environment:
          PATH: "{{ extract_dest }}"/go/bin
        register: version

      - name: Display go version
        debug: 
          msg: "{{ version.stdout_lines }}"
        
