---
- name: Run hello world 
  hosts: app
  tasks:
      - name: Run hello.go
        command: go run "{{ filename }}"
        environment:
          PATH: '/usr/local/go/bin'
        vars:
          filename: /home/go/hello.go
        register: hello_out

      - name: Display go version
        debug: 
          msg: "{{ hello_out.stdout_lines }}"
