- name: Configure Nginx
  gather_facts: false
  hosts: vms
  become: yes
  become_method: sudo

  tasks:
    - name: Install nginx
      yum: 
        name: nginx
        state: latest
      register: insvar

    - name: Display Output
      debug:
        msg: "{{ insvar.results }}"

